
import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javafx.scene.control.PasswordField;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rohan
 */
public class fees_status extends javax.swing.JFrame {
    
    


    /**
     * Creates new form fees_status
     */
    public fees_status() {
        initComponents();
      fees_nr();
      fees_r();
      fees_p();
      this.getContentPane().setBackground(Color.WHITE);
      this.setTitle("fees status ~ evolution language institute");
        
   
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(255, 0, 0));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        )

    );
    jTable1.setToolTipText("Students who hand NOT paid the fees");
    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            jTable1MouseEntered(evt);
        }
        public void mousePressed(java.awt.event.MouseEvent evt) {
            jTable1MousePressed(evt);
        }
        public void mouseReleased(java.awt.event.MouseEvent evt) {
            jTable1MouseReleased(evt);
        }
    });
    jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            jTable1KeyPressed(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jTable2.setBackground(new java.awt.Color(51, 255, 51));
    jTable2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jTable2.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
    ));
    jTable2.setToolTipText("Students who had PAID the fees FULLY");
    jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable2MouseClicked(evt);
        }
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            jTable2MouseEntered(evt);
        }
    });
    jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            jTable2KeyPressed(evt);
        }
    });
    jScrollPane2.setViewportView(jTable2);

    jTable3.setBackground(new java.awt.Color(153, 0, 153));
    jTable3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jTable3.setForeground(new java.awt.Color(255, 255, 255));
    jTable3.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Title 1", "Title 2", "Title 3", "Title 4"
        }
    ));
    jTable3.setToolTipText("Students who had paid the fees PARTIALLY");
    jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseEntered(java.awt.event.MouseEvent evt) {
            jTable3MouseEntered(evt);
        }
    });
    jTable3.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            jTable3KeyPressed(evt);
        }
    });
    jScrollPane3.setViewportView(jTable3);

    jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(255, 51, 51));
    jLabel1.setText("FEES NOT RECEIVED");

    jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(51, 255, 51));
    jLabel2.setText("FEES RECEIVED");

    jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(153, 0, 153));
    jLabel3.setText("FEES PARTIALLY RECEIVED");

    jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Storm-Group-Consultancy_logo.jpg"))); // NOI18N

    jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/Refresh_64px.png"))); // NOI18N
    jLabel5.setText("Refresh");
    jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel5MouseClicked(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(205, 205, 205)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2)
            .addGap(249, 249, 249))
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGroup(layout.createSequentialGroup()
                    .addGap(182, 182, 182)
                    .addComponent(jLabel3)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGroup(layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(jLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                    .addComponent(jLabel4)))
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked

    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed

    }//GEN-LAST:event_jTable1MousePressed

    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
    // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseReleased

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER)
{
  
  
     DefaultTableModel    df=(DefaultTableModel)jTable1.getModel();
int sno=(int) df.getValueAt(jTable1.getSelectedRow(),0);

get_fees gf=new get_fees();
gf.fees(sno);

}// TODO add your handling code here:
    }//GEN-LAST:event_jTable1KeyPressed

    private void jTable2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyPressed
      if(evt.getKeyCode()==KeyEvent.VK_ENTER)
{
  
  
     DefaultTableModel    df=(DefaultTableModel)jTable2.getModel();
int sno=(int) df.getValueAt(jTable2.getSelectedRow(),0);

get_fees gf=new get_fees();
gf.fees(sno);

}  // TODO add your handling code here:
    }//GEN-LAST:event_jTable2KeyPressed

    private void jTable3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable3KeyPressed
if(evt.getKeyCode()==KeyEvent.VK_ENTER)
{
  
  
     DefaultTableModel    df=(DefaultTableModel)jTable3.getModel();
int sno=(int) df.getValueAt(jTable3.getSelectedRow(),0);

get_fees gf=new get_fees();
gf.fees(sno);

}        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3KeyPressed

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
jTable2.getSelectionModel().clearSelection();     
jTable3.getSelectionModel().clearSelection();  // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseEntered

    private void jTable2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseEntered
jTable1.getSelectionModel().clearSelection();  
jTable3.getSelectionModel().clearSelection();  // TODO add your handling code here:
    }//GEN-LAST:event_jTable2MouseEntered

    private void jTable3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseEntered
jTable2.getSelectionModel().clearSelection();  
jTable1.getSelectionModel().clearSelection();  // TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseEntered

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
if(evt.getKeyCode()==KeyEvent.VK_F5)
{
    fees_nr();
    fees_r();
    fees_p();
}// TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
fees_r();
fees_p();
fees_nr();// TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fees_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fees_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fees_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fees_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fees_status().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables

public void fees_nr()
{
     String host="jdbc:mysql://localhost:3306/eli";
    String username="root";
    String password="12345";
    
    Statement stmt=null;
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    String nr="NOT RECEIVED !";
    String r="RECEIVED !";
    try
    {
        con=DriverManager.getConnection(host,username,password);
  String q="select record.student_no,name,reg_date,course from record,fees where record.student_no=fees.student_no and fees.fees_received=0;";
  
  pst=con.prepareStatement(q);
  rs=pst.executeQuery();
  jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    }
   catch(Exception e)
   {JOptionPane.showMessageDialog(this,e.getMessage());}
}

public void fees_r()
{
     String host="jdbc:mysql://localhost:3306/eli";
    String username="root";
    String password="12345";
    
    Statement stmt=null;
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    String nr="NOT RECEIVED !";
    String r="RECEIVED !";
    try
    {
        con=DriverManager.getConnection(host,username,password);
  String q1="select record.student_no,name,reg_date,course from record,fees where record.student_no=fees.student_no and record.pay-fees.fees_received=0;";
  
  pst=con.prepareStatement(q1);
  rs=pst.executeQuery();
  jTable2.setModel(DbUtils.resultSetToTableModel(rs));
    }
   catch(Exception e)
   {JOptionPane.showMessageDialog(this,e.getMessage());}
}

public void fees_p()
{
     String host="jdbc:mysql://localhost:3306/eli";
    String username="root";
    String password="12345";
    
    Statement stmt=null;
    Connection con=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    String nr="NOT RECEIVED !";
    String r="RECEIVED !";
    String p="PENDING !";
    try
    {
        con=DriverManager.getConnection(host,username,password);
  String q2="select record.student_no,name,reg_date,course from record,fees where record.student_no=fees.student_no and fees.fees_received<record.pay and fees.fees_received>0;";
  
  pst=con.prepareStatement(q2);
  rs=pst.executeQuery();
  jTable3.setModel(DbUtils.resultSetToTableModel(rs));
    }
   catch(Exception e)
   {JOptionPane.showMessageDialog(this,e.getMessage());}
}
}
