
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.PrintWriter;
import java.io.Writer;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author rohan
 */

public class update_fees extends javax.swing.JFrame {

    /**
     * Creates new form update_fees
     */
    public update_fees() throws ClassNotFoundException, SQLException {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        get_fees();
     hidden_ielts.setVisible(false);
     hidden_grammar.setVisible(false);
     hidden_se.setVisible(false);
     hidden_toefl.setVisible(false);
     hidden_pte.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        hidden_ielts = new javax.swing.JLabel();
        hidden_grammar = new javax.swing.JLabel();
        hidden_se = new javax.swing.JLabel();
        hidden_toefl = new javax.swing.JLabel();
        hidden_pte = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Update fees !");

        jLabel2.setText("IELTS");

        jLabel3.setText("Grammar");

        jLabel4.setText("Spoken english");

        jLabel5.setText("TOEFL");

        jLabel6.setText("PTE ");

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        hidden_ielts.setText("jLabel7");

        hidden_grammar.setText("jLabel7");

        hidden_se.setText("jLabel7");

        hidden_toefl.setText("jLabel7");

        hidden_pte.setText("jLabel7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hidden_toefl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(hidden_grammar))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField2))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hidden_ielts)
                            .addComponent(hidden_se)
                            .addComponent(hidden_pte))))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(hidden_ielts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hidden_grammar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hidden_se)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hidden_toefl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(7, 7, 7)
                .addComponent(hidden_pte))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int ielts=Integer.parseInt(jTextField1.getText());
int grammar=Integer.parseInt(jTextField2.getText());
int se=Integer.parseInt(jTextField3.getText());
int toefl=Integer.parseInt(jTextField4.getText());
int pte=Integer.parseInt(jTextField5.getText());

try
{
    String i=jTextField1.getText();
    String g=jTextField2.getText();
    String spoken=jTextField3.getText();
    String t=jTextField4.getText();
    String p=jTextField5.getText();
     DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
Date date = new Date();

    FileWriter fw=null;
      
            File file=new File("D:/FEES_LOGS.txt");
            fw = new FileWriter(file,true);
            PrintWriter pw=new PrintWriter(fw);
            pw.println("******************************************************");
            pw.print("date: "); pw.println(""+dateFormat.format(date));

            pw.println("");
            pw.println("");
            
            pw.println("IELTS: Form- "+hidden_ielts.getText()+" To- "+i);
            pw.println("Grammar: Form- "+hidden_grammar.getText()+" To- "+g);
            pw.println("Spoken english: Form- "+hidden_se.getText()+" To- "+spoken);
            pw.println("TOEFL: Form- "+hidden_toefl.getText()+" To- "+t);
            pw.println("PTE: Form- "+hidden_pte.getText()+" To- "+p);
            pw.println("");
              pw.println("******************************************************");
            pw.close();
    Class.forName("java.sql.DriverManager");
    Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/eli","root","12345");
    Statement s=(Statement)c.createStatement();
    String q="update official_fees set fees="+ielts+" where course='IELTS';";
    String q1="update official_fees set fees="+grammar+" where course='Grammar';";
    String q3="update official_fees set fees="+se+" where course='Spoken english';";
    String q4="update official_fees set fees="+toefl+" where course='TOEFL';";
    String q5="update official_fees set fees="+pte+" where course='PTE';";
    s.executeUpdate(q);
    s.executeUpdate(q1);
    s.executeUpdate(q5);
    s.executeUpdate(q3);
    s.executeUpdate(q4);
    JOptionPane.showMessageDialog(this,"FEES UPDATED SUCCESSFULLY");
    
    get_fees();
    
}
catch(Exception e)
{JOptionPane.showMessageDialog(this,e.getMessage());

}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_fees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new update_fees().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(update_fees.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(update_fees.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hidden_grammar;
    private javax.swing.JLabel hidden_ielts;
    private javax.swing.JLabel hidden_pte;
    private javax.swing.JLabel hidden_se;
    private javax.swing.JLabel hidden_toefl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables

private void get_ielts() throws ClassNotFoundException, SQLException
{
    Class.forName("java.sql.DriverManager");
    Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/eli","root","12345");
    Statement s=(Statement)c.createStatement();
    String q="select*from official_fees where course='IELTS';";
    ResultSet rs=s.executeQuery(q);
    if(rs.next())
    {
        String ielts=rs.getString("fees");
        jTextField1.setText(""+ielts);
        hidden_ielts.setText(""+ielts);
        
    }
}
private void get_grammar() throws ClassNotFoundException, SQLException
{
    Class.forName("java.sql.DriverManager");
    Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/eli","root","12345");
    Statement s=(Statement)c.createStatement();
    String q="select*from official_fees where course='Grammar';";
    ResultSet rs=s.executeQuery(q);
    if(rs.next())
    {
        String ielts=rs.getString("fees");
        jTextField2.setText(""+ielts);
        hidden_grammar.setText(""+ielts);
        
    }
}
private void get_se() throws ClassNotFoundException, SQLException
{
    Class.forName("java.sql.DriverManager");
    Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/eli","root","12345");
    Statement s=(Statement)c.createStatement();
    String q="select*from official_fees where course='Spoken english';";
    ResultSet rs=s.executeQuery(q);
    if(rs.next())
    {
        String ielts=rs.getString("fees");
        jTextField3.setText(""+ielts);
        hidden_se.setText(""+ielts);
        
    }
}
private void get_toefl() throws ClassNotFoundException, SQLException
{
    Class.forName("java.sql.DriverManager");
    Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/eli","root","12345");
    Statement s=(Statement)c.createStatement();
    String q="select*from official_fees where course='TOEFL';";
    ResultSet rs=s.executeQuery(q);
    if(rs.next())
    {
        String ielts=rs.getString("fees");
        jTextField4.setText(""+ielts);
        hidden_toefl.setText(""+ielts);
        
    }
}
private void get_pte() throws ClassNotFoundException, SQLException
{
    Class.forName("java.sql.DriverManager");
    Connection c=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/eli","root","12345");
    Statement s=(Statement)c.createStatement();
    String q="select*from official_fees where course='PTE';";
    ResultSet rs=s.executeQuery(q);
    if(rs.next())
    {
        String ielts=rs.getString("fees");
        jTextField5.setText(""+ielts);
        hidden_pte.setText(""+ielts);
        
    }
}

private void get_fees() throws ClassNotFoundException, SQLException
{
    get_ielts();
    get_grammar();
    get_se();
    get_toefl();
    get_pte();
}

}
